/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mecsyco_core_model_CppModelArtifact */

#ifndef _Included_mecsyco_core_model_CppModelArtifact
#define _Included_mecsyco_core_model_CppModelArtifact
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mecsyco_core_model_CppModelArtifact
 * Method:    n_ModelArtifact
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_mecsyco_core_model_CppModelArtifact_n_1ModelArtifact
  (JNIEnv *, jobject);

/*
 * Class:     mecsyco_core_model_CppModelArtifact
 * Method:    n_processInternalEvent
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_mecsyco_core_model_CppModelArtifact_n_1processInternalEvent
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     mecsyco_core_model_CppModelArtifact
 * Method:    n_getNextInternalEventTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_mecsyco_core_model_CppModelArtifact_n_1getNextInternalEventTime
  (JNIEnv *, jobject);

/*
 * Class:     mecsyco_core_model_CppModelArtifact
 * Method:    n_getLastEventTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_mecsyco_core_model_CppModelArtifact_n_1getLastEventTime
  (JNIEnv *, jobject);

/*
 * Class:     mecsyco_core_model_CppModelArtifact
 * Method:    n_processExternalInputEvent
 * Signature: (Ljava/lang/String;DLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mecsyco_core_model_CppModelArtifact_n_1processExternalInputEvent
  (JNIEnv *, jobject, jstring, jdouble, jstring);

/*
 * Class:     mecsyco_core_model_CppModelArtifact
 * Method:    n_getExternalOutputEvent
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_mecsyco_core_model_CppModelArtifact_n_1getExternalOutputEvent
  (JNIEnv *, jobject, jstring);

/*
 * Class:     mecsyco_core_model_CppModelArtifact
 * Method:    n_initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mecsyco_core_model_CppModelArtifact_n_1initialize
  (JNIEnv *, jobject);

/*
 * Class:     mecsyco_core_model_CppModelArtifact
 * Method:    n_finishSimulation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mecsyco_core_model_CppModelArtifact_n_1finishSimulation
  (JNIEnv *, jobject);

/*
 * Class:     mecsyco_core_model_CppModelArtifact
 * Method:    n_setInitialParameters
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mecsyco_core_model_CppModelArtifact_n_1setInitialParameters
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
